/**
 * `release status` — one screen of where everything stands.
 * `release checklist` — the same facts as a filled-in runbook (markdown on
 * stdout), one line per action with the exact command.
 */

import {
	DOCKER_WORKFLOW,
	DockerInfo,
	MASTER,
	PROGRAMS,
	dockerDefs,
	dockerInfo,
	infraDir,
	infraStages,
	packages,
	pendingChangesets,
	pinnedVersions,
	programInfo,
	versionPackagesPr,
} from './inventory';
import { originMasterSha, semverCmp } from './sh';
import {
	bold,
	dim,
	done,
	green,
	header,
	line,
	red,
	section,
	shortDate,
	shortSha,
	table,
	yellow,
} from './ui';

const BANG = yellow('(!)');

function runMark(conclusion: string | undefined, url?: string): string {
	if (!conclusion) return dim('no run');
	const mark =
		conclusion === 'success'
			? green('✓')
			: conclusion === 'in_progress' || conclusion === ''
			? yellow('…')
			: red('✗');
	return url ? `${mark} ${dim(url.replace(/.*\/runs\//, 'run '))}` : mark;
}

function pins(app: string): string[] {
	return infraStages().map((s) => {
		const v = pinnedVersions(s, app);
		return v.length ? `${s.stage}=${v.join('/')}` : `${s.stage}=–`;
	});
}

export function status(): void {
	const sha = originMasterSha();
	header('release status', `${MASTER} ${shortSha(sha)}`);

	// programs
	section('programs');
	const programs = PROGRAMS.filter((p) => p.mainnet).map((p) => programInfo(p));
	const rows: string[][] = [];
	for (const p of programs) {
		rows.push([
			bold(p.def.name),
			`Cargo ${p.cargoVersion}`,
			p.lastTag
				? `tag v${p.lastTagVersion} @${shortSha(p.lastTagSha)} ${dim(
						shortDate(p.lastTagDate)
				  )}`
				: dim('never tagged'),
			`mainnet ${runMark(p.mainnetRun?.conclusion)}`,
			`${p.commitsSinceTag.length} program commit(s) since tag`,
		]);
	}
	table(rows);
	const devnet = programs[0]?.devnetRun;
	if (devnet) {
		line(
			`devnet last deploy run ${runMark(devnet.conclusion)} @${shortSha(
				devnet.headSha
			)} ${dim(shortDate(devnet.createdAt))}` +
				(programs[0].devnetBehind !== undefined
					? ` ${dim(`(${programs[0].devnetBehind} commits behind master)`)}`
					: '')
		);
	}
	for (const p of programs) {
		if (p.needsBump) {
			line(
				`${BANG} ${p.def.name}: Cargo ${p.cargoVersion} is not ahead of tag v${p.lastTagVersion}; run \`release program bump ${p.def.name}\` before tagging`
			);
		}
		for (const w of p.warnings) line(`${BANG} ${p.def.name}: ${w}`);
		for (const c of p.commitsSinceTag.slice(0, 8)) {
			line(`${dim(p.def.name)}  ${c.sha} ${c.subject}`);
		}
	}

	// npm
	section('npm packages');
	const pkgs = packages();
	table(
		pkgs.map((p) => [
			bold(p.dir),
			p.version,
			p.tagged
				? green('tagged')
				: p.ciSkipped
				? dim('untagged (CI skips this package)')
				: `${BANG} untagged: \`release npm ${p.dir}\``,
			p.lastTag ? dim(`last ${p.lastTag}`) : dim('never tagged'),
		])
	);
	const pr = versionPackagesPr();
	const pending = pendingChangesets();
	if (pr) {
		line(
			`${BANG} Version Packages PR #${pr.number} open ${dim(
				pr.url
			)} — merge it, then \`release npm\``
		);
	} else if (pending.length) {
		line(
			`${pending.length} changeset(s) waiting for the bot PR: ${pending.join(
				', '
			)}`
		);
	}

	// docker
	section('docker images');
	const stages = infraStages();
	const dockers = dockerDefs().map(dockerInfo);
	table(
		dockers.map((d) => [
			bold(d.def.app),
			d.lastTag
				? `v${d.lastVersion} @${shortSha(d.lastSha)} ${dim(
						shortDate(d.lastDate)
				  )}`
				: dim('never tagged'),
			`${d.commitsSince.length} commit(s) since`,
			...(stages.length ? pinsCell(d) : []),
		])
	);
	if (!infraDir()) {
		line(
			dim('pass --infra <path> (or VELOCITY_INFRA_DIR) to compare gitops pins')
		);
	}
	done(dim(`publish workflow: ${DOCKER_WORKFLOW}`));
}

function pinsCell(d: DockerInfo): string[] {
	return pins(d.def.app).map((cell) => {
		const v = cell.split('=')[1];
		const behind =
			v !== '–' && d.lastVersion && semverCmp(v, d.lastVersion) < 0;
		return behind ? `${cell} ${BANG}` : cell;
	});
}

function box(s: string): string {
	return `- [ ] ${s}`;
}

export function checklist(): void {
	const sha = originMasterSha();
	const out: string[] = [];
	const programs = PROGRAMS.filter((p) => p.mainnet).map((p) =>
		programInfo(p, false)
	);
	const pkgs = packages();
	const pr = versionPackagesPr();
	const dockers = dockerDefs().map(dockerInfo);
	const changed = dockers.filter((d) => d.commitsSince.length > 0);
	// stages that actually pin one of our images (staging carries none)
	const stages = infraStages().filter((s) =>
		dockers.some((d) => pinnedVersions(s, d.def.app).length > 0)
	);
	const infra = infraDir() ? ` --infra ${infraDir()}` : '';

	out.push(`# Release checklist — ${MASTER} @ ${shortSha(sha)}`);
	out.push('');
	out.push(
		'Generated by `bun run release checklist`. Every command below is read-only until `--execute` is added.'
	);
	out.push('');

	out.push('## 1. Prep (velocity-v1, master)');
	if (pr) {
		out.push(box(`merge Version Packages PR #${pr.number}: ${pr.url}`));
	}
	const untagged = pkgs.filter((p) => !p.tagged && !p.ciSkipped);
	out.push(
		box(
			untagged.length
				? `publish npm: \`bun run release npm --execute\` (${untagged
						.map((p) => `${p.dir} ${p.version}`)
						.join(', ')})`
				: 'npm: nothing untagged (re-check after the Version Packages merge)'
		)
	);
	for (const p of programs) {
		if (p.commitsSinceTag.length === 0) continue;
		const next = p.needsBump ? '' : ` (Cargo already at ${p.cargoVersion})`;
		out.push(
			box(
				p.needsBump
					? `bump ${p.def.name}: \`bun run release program bump ${p.def.name} --execute\` → PR → merge`
					: `${p.def.name} version bump already landed${next}`
			)
		);
		for (const w of p.warnings) out.push(`  - ⚠ ${w}`);
	}
	out.push(
		box(
			changed.length
				? `docker images: \`bun run release docker ${changed
						.map((d) => d.def.app)
						.join(' ')} --execute\` (${changed
						.map((d) => `${d.def.app} → v${d.nextVersion}`)
						.join(', ')})`
				: 'docker: no image has changes since its last tag'
		)
	);
	out.push('');

	out.push('## 2. Devnet');
	for (const p of programs) {
		if (p.commitsSinceTag.length === 0) continue;
		for (const w of p.warnings) {
			out.push(
				box(`devnet pre-stage: ${w} (\`velocity-admin -e devnet ...\`)`)
			);
		}
		out.push(
			box(
				`deploy ${p.def.name}: \`bun run release program devnet ${p.def.name} --execute\` (dispatches CI, watches, runs verify-buffer --devnet)`
			)
		);
		out.push(box(`approve + execute the devnet Squads proposal`));
		out.push(
			box(
				`verify: \`solana program show <program-id> -u <devnet rpc>\`, \`velocity-admin -e devnet show state\``
			)
		);
	}
	const devStages = stages.filter((s) => s.env !== 'prod');
	if (changed.length) {
		out.push(
			box(
				`infra pins: \`bun run release infra ${
					devStages.map((s) => s.stage).join(' ') || 'master'
				}${infra} --execute\` → merge the deploy PR → ArgoCD syncs`
			)
		);
	}
	out.push('');

	out.push('## 3. Mainnet');
	for (const p of programs) {
		if (p.commitsSinceTag.length === 0) continue;
		for (const w of p.warnings) {
			out.push(
				box(`mainnet pre-stage: ${w} (\`velocity-admin ... --multisig <pda>\`)`)
			);
		}
		const ver = p.needsBump ? '<bumped version>' : p.cargoVersion;
		out.push(
			box(
				`tag + release ${p.def.name}: \`bun run release program mainnet ${p.def.name} --execute\` (pushes program-${p.def.name}-v${ver}, watches, runs verify-buffer)`
			)
		);
		out.push(box(`approve + execute the mainnet Squads proposal`));
		out.push(box(`verify on mainnet the same way as devnet`));
	}
	const prodStages = stages.filter((s) => s.env === 'prod');
	if (changed.length) {
		out.push(
			box(
				`infra pins: \`bun run release infra ${
					prodStages.map((s) => s.stage).join(' ') || 'mainnet-beta'
				}${infra} --execute\` → merge → then the infra master → mainnet-beta release PR → prod ArgoCD`
			)
		);
	}
	out.push('');
	process.stdout.write(out.join('\n') + '\n');
}
