use std::path::Path;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    if std::env::var("DOCS_RS").is_ok() {
        println!("cargo:warning=docs.rs build detected. skipping idl-gen");
        return Ok(());
    }
    let current_dir = std::env::current_dir()?.canonicalize()?;

    // Generate IDL types from the canonical program IDL committed under the SDK
    // package, regenerated by `bun run program:idl`. This is the single source of
    // truth shared with the TypeScript SDK. (Pre-monorepo, velocity-rs lived in a
    // separate repo and vendored a fetched copy under res/velocity.json; the
    // monorepo makes that copy — and its drift — unnecessary.)
    let idl_source_path = current_dir.join("../../packages/sdk/src/idl/velocity.json");
    let idl_mod_path = current_dir.join("crates/src/velocity_idl.rs");

    // The IDL only exists when building inside the monorepo checkout. A packaged
    // or vendored copy of this crate won't have it — fall back to the committed
    // crates/src/velocity_idl.rs, which CI keeps in sync with the IDL.
    if !idl_source_path.exists() {
        println!(
            "cargo:warning=program IDL not found at {}; using committed velocity_idl.rs",
            idl_source_path.display()
        );
        return Ok(());
    }

    // Only emit rerun-if-changed when the IDL exists: pointing it at a missing
    // path would make cargo rerun this script on every build.
    println!("cargo:rerun-if-changed=../../packages/sdk/src/idl/velocity.json");
    generate_idl_types(&idl_source_path, idl_mod_path.as_path())?;
    Ok(())
}

fn generate_idl_types(
    idl_source_path: &Path,
    idl_mod_path: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let idl_mod_rs = velocity_idl_gen::generate_rust_types(idl_source_path)
        .map_err(|err| format!("generating IDL failed: {err:?}"))?;

    // Skip the write when the committed file is already current. Consumers may
    // build from a read-only or checksum-verified source dir (cargo vendor, Nix),
    // where a gratuitous rewrite fails the build or invalidates checksums.
    if std::fs::read(idl_mod_path).ok().as_deref() == Some(idl_mod_rs.as_bytes()) {
        return Ok(());
    }
    std::fs::write(idl_mod_path, idl_mod_rs)?;
    Ok(())
}
